### PR TITLE
Add constructor for type Language accepting a string

### PR DESCRIPTION
**Pull request by dcecchini**
I propose this to be able to programmatically create Language objects according to a variable (e.g.: `lang="English"` or `lang="eng"`). 

Example:

```julia
function get_stopwords(lang="English")
    stopwords(Language(lang))
end
```

We can call as:

```julia
get_stopwords("English")
get_stopwords("eng")
get_stopwords("Portuguese")
get_stopwords("Italian") # Any language on the subtypes of Language
```

The string can be the English name of the language or its iso code.  I use this on my text pre-processing functions when I allow the text to be generic.

### CODE REVIEW

**Comment by aviks** [comment]
Sorry for missing this. This feature is useful, but I'd like a few tests before merging this.

**Comment by dcecchini** [comment]
Hi @aviks did you had the time to check?

**Comment by aviks** [comment]
What I meant was that I would need some unittests to be added to this PR that tests the new functionality.

**Comment by dcecchini** [comment]
Hi @aviks , sorry for the big delay in working on this. I just added some unit tests, please let me know if those are enough.

The tests can be found at `test/string_to_language.jl`, and I also created the test set at the `runtests.jl` file.

**Comment by aviks** [comment]
Thanks!

**Pull request merged**
