### PR TITLE
Indian and other Languages stopwords

### PR DESCRIPTION
**Pull request by aquatiko**
StopWords based on [stopwords-iso](https://github.com/stopwords-iso)
I will be adding some tests shortly!!

### CODE REVIEW

**Comment by aviks** [comment]
This is cool, thanks!

Would it be possible to add stopwords from all languages in `stopwords-iso` (for the languages that we have support for in this package)? It'll be painful to do this manually, but maybe we can generate this? 

Also, we need to add an acknowledgement to the original source somewhere.

**Comment by aquatiko** [comment]
@aviks I think tests won't be necessary for these raw data files. I have added all the languages stopwords from `stopwords-iso`. I think we should mention about the acknowledgement in the `README.md` or the `LICESENCE.md` file here. It had a MIT license there.

**Comment by aviks** [comment]
Let's have a LICENSE.md in the `stopwords` directory saying

```
Bengali
Basque
...
...

Stopwords lists for the above languages are copied from https://github.com/stopwords-iso/stopwords-iso and are provided under the following licence

The MIT License (MIT)

Copyright (c) 2016 Gene Diaz

Permission is hereby granted, free of charge, to any person obtaining a copy
........<rest of MIT license verbatim>
```

**Comment by aquatiko** [comment]
@aviks I was wondering how a user can see a list of all supported languages?

**Comment by aquatiko** [comment]
Accidentally closed it

**Comment by aviks** [comment]
>I was wondering how a user can see a list of all supported languages?

`subtypes(Language)` shows all supported languages. Perhaps we should provide an api for that, and document the list.

**Pull request merged**
